const PROGRESS_BAR_SHOW_ANIMATION_DURATION_MS: number = 300;
const PROGRESS_BAR_MOVE_ANIMATION_DURATION_MS: number = 500;

export { PROGRESS_BAR_SHOW_ANIMATION_DURATION_MS, PROGRESS_BAR_MOVE_ANIMATION_DURATION_MS };
